---
abstract: 'Perl Dancer2 plugin for interaction with key-value-store Redis.'
author:
  - 'BURNERSK <burnersk@cpan.org>'
build_requires:
  Dancer2: '0'
  Dancer2::Plugin::Redis: '0'
  HTTP::Request::Common: '0'
  Plack::Builder: '0'
  Plack::Test: '0'
  Test::More: '0'
  Test::NoWarnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.141520'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dancer2-Session-Redis
no_index:
  directory:
    - example
    - t
provides:
  Dancer2::Session::Redis:
    file: lib/Dancer2/Session/Redis.pm
    version: '0.002'
  Dancer2::Session::Redis::Serialization::Sereal:
    file: lib/Dancer2/Session/Redis/Serialization/Sereal.pm
    version: '0.001'
  Dancer2::Session::Redis::SerializationRole:
    file: lib/Dancer2/Session/Redis/SerializationRole.pm
    version: '0.001'
recommends:
  Sereal: '0'
requires:
  Carp: '0'
  Dancer2::Core::Role::SessionFactory: '0'
  Dancer2::Core::Types: '0'
  Moo: '0'
  Moo::Role: '0'
  Redis: '0'
  Safe::Isa: '0'
  Try::Tiny: '0'
  Type::Tiny: '0'
  perl: '5.013002'
  strictures: '0'
resources:
  bugtracker: https://github.com/burnersk/Dancer2-Session-Redis/issues
  homepage: https://github.com/burnersk/Dancer2-Session-Redis
  repository: https://github.com/burnersk/Dancer2-Session-Redis.git
version: '0.002'
x_contributors:
  - 'BURNERSK <burnersk@cpan.org>'
  - 'SIMBABQUE <simbabque@cpan.org>'
